default-resources:
    - cpus=2
    - mem_mb=512
    - time_min=5
resources: mem_mb=16000
jobs: 1000
max-jobs-per-second: 10
max-status-checks-per-second: 10
latency-wait: 60
restart-times: 0
printshellcmds: True
use-singularity: True
singularity-args: "--bind $HOME,/home/jpmcgeown/github,/home/jpmcgeown/data"
use-conda: True
conda-frontend: "conda"
