configfile: 'config/config.yml'

module preprocessing:
    snakefile:
        "rules/preprocessing.smk"
    config: config

use rule * from preprocessing as preprocessing_*

module tidy_snake:
    snakefile:
        github("MataiMRI/tidySnake", path="workflow/Snakefile", commit="1726b4d")  # TODO use tag
    config: config

use rule * from tidy_snake as tidy_snake_*

rule all:
    localrule: True
    default_target: True
    input:
        rules.tidy_snake_all.input,
        # rules.preprocessing_all.input,
