##permissions workaround sudo chmod -R 777 ./

## NeSI project account
account: uoa03264

## Data import
ethics_prefix: Conc_20Ntb14_

## Directories
datadir: /nesi/nobackup/uoa03264/fMRIpipeline_data/dicom_test
resultsdir: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test

#Dicom directory structure can be flexible but MUST include {{subject}} and {{session}}
dicom_dir_structure: /dicom/sub_{{subject}}/ses_{{session}}/*/* # GET THIS WORKING FOR HEUDICONV
dicom_compression_ext: .zip

## Scan info
rep_time: 1.5

#FREESURFER_HOME: /usr/local/freesurfer

# TASK
# will need to include something in first_level.py to account for different tasks

## License
fs_license: "/LICENSE.txt"

## FMRIPREP settings
nthreads: 8
mem: 20000
fs_status: --fs-subjects
                      # Leave blank to run freesurfer within fmriprep
  # --fs-no-reconall    # Select this option to skip freesurfer or blank space to run freesurfer
  # --fs-subjects     # Select this option if you have prerun Freesurfer

fs_dir: /bids/derivatives/freesurfer # Directory where pre-run freesurfer results can be found

## Filtering and smooth settings
high_pass: 0.01
low_pass: 0.1
fwhm: 6

## False detection rate alpha
fdr_alpha: 0.01
## Functional connectivity threshold
func_conn_thresh: 0.25

## Confounds to extract
confound_info:
  num_confounds: 9
  confounds:
  - csf
  - white_matter
  - trans_x
  - trans_y
  - trans_z
  - rot_x
  - rot_y
  - rot_z
  - framewise_displacement

## Framewise displacement threshold for accepting
fd_thresh: 0.5

## List of one or more resting state networks for first level
network_info:
  num_networks: 2
  networks:
    - DMN
    - Salience
