## NeSI project account
account: uoa03264

## Data import
ethics_prefix: Conc_20Ntb14_

## Directories
datadir: /nesi/nobackup/uoa03264/fMRIpipeline_data/dicom_josh
resultsdir: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_long

#Dicom directory structure can be flexible but MUST include {{subject}} and {{session}}
dicom_dir_structure: /dicom/sub_{{subject}}/ses_{{session}}/*/* # GET THIS WORKING FOR HEUDICONV
dicom_compression_ext: .zip

## Scan info
rep_time: 1.5

# TASK
# will need to include something in first_level.py to account for different tasks

freesurfer:
  license_path: ./license.txt
  mem_mb: 4000
  time_min: 540
  threads: 8

fmriprep:
  mem_mb: 25000
  time_min: 180
  threads: 8

## Confounding (nuisance) variables to be regressed out of signal to improve SNR
confound_var:
  num_confounds: 9
  confounds:
  - csf
  - white_matter
  - trans_x
  - trans_y
  - trans_z
  - rot_x
  - rot_y
  - rot_z
  - framewise_displacement

preprocessing:
    frame_disp_thresh: 0.5 ## Framewise displacement threshold for accepting
    high_pass: 0.01 ## Set high and low range of bandpass filter
    low_pass: 0.1
    smooth_fwhm: 6 #size of smoothing kernel in mm

resting_first_level:
    fdr_alpha: 0.01 ## False detection rate alpha
    func_conn_thresh: 0.25 ## Functional connectivity threshold

## List of one or more resting state networks for first level
network_info:
  num_networks: 2
  networks:
    - DMN
    - Salience
    
# TASK
# will need to include something in first_level.py to account for different tasks
#task_first_level:
#    fdr_alpha:
