# Specify a prefix on filenames to be stripped during processing i.e. ethics approval
ethics_prefix: "ETHICS_PREFIX_"  # you need to specify yours here

# Input and output directories
datadir: "DICOM_FOLDER"  # you need to specify yours here
resultsdir: "RESULTS_FOLDER"  # you need to specify yours here

# Toggle longitudinal processing steps in Freesurfer and fMRIprep
use_longitudinal: False

# Rule resources
heudiconv:
    heuristic: "HEURISTIC_SCRIPT.py"  # you need to specify your script here
    mem_mb: 4000
    time_min: 120
    threads: 2

mriqc:
    mem_mb: 16000
    time_min: 120
    threads: 8

freesurfer:
    license_path: "LICENCE_FILE"  # you need to specify yours here
    mem_mb: 4000
    time_min: 660
    threads: 8

fmriprep:
    mem_mb: 25000
    time_min: 180
    threads: 16
    workdir: "TEMPORARY_FOLDER"  # you need to specify yours here

first_level:
    mem_mb: 12000
    time_min: 10
    threads: 2

    # scan info
    rep_time: TR  # you need to specify yours here, as an integer

    # confounding (nuisance) variables to be regressed out of signal to improve SNR
    confounds:
        - csf
        - white_matter
        - trans_x
        - trans_y
        - trans_z
        - rot_x
        - rot_y
        - rot_z

    preprocessing:
        # framewise displacement threshold for accepting
        frame_disp_thresh: 0.5
        # set high and low range of bandpass filter
        high_pass: 0.01
        low_pass: 0.1
        # size of smoothing kernel in mm
        smooth_fwhm: 6

    # Atlas and list of one or more resting state networks for first level analysis
    atlas_info:
        image: atlas/MSDL_rois/msdl_rois.nii
        labels: atlas/MSDL_rois/msdl_rois_labels.csv
        networks:
            - DMN
            - Salience

    resting_first_level:
        # false detection rate alpha
        fdr_alpha: 0.99
        # functional connectivity threshold
        func_conn_thresh: 0.25
