cluster-sync:
    mkdir -p logs &&
    nesi/submit.py
        --partition milan
        --account {config[account]}
        --time {resources.time_min}
        --mem {resources.mem_mb}
        --cpus-per-task {resources.cpus}
        --output nesi/logs/%j-{rule}.out
        --error nesi/logs/%j-{rule}.out
        --job-name snakejob-{rule}
default-resources:
    - cpus=1
    - mem_mb=512
    - time_min=5
jobs: 1000
max-jobs-per-second: 10
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 20
restart-times: 0
printshellcmds: True
use-singularity: True
singularity-args: "--cleanenv --bind $HOME,/nesi/project,/nesi/nobackup,/scale_wlg_persistent,/scale_wlg_nobackup"
use-conda: True
conda-frontend: "conda"
